# Generated by Django 2.2.3 on 2019-08-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20190811_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auhtor',
            new_name='Author',
        ),
    ]
