# Generated by Django 2.2.3 on 2019-08-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20190811_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Auhtor',
        ),
    ]
